# Generated by Django 2.1.2 on 2020-04-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_tag',
            name='service_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service_Categories'),
        ),
    ]
