# Generated by Django 2.1.2 on 2020-04-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200428_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_tag',
            name='service_categories',
        ),
        migrations.DeleteModel(
            name='Service_Categories',
        ),
        migrations.DeleteModel(
            name='Service_Tag',
        ),
    ]
