# Generated by Django 2.1.2 on 2020-04-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200428_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('service_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service_Categories')),
            ],
        ),
    ]
