# Generated by Django 2.1.2 on 2020-04-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Service_Head',
        ),
    ]
