# Generated by Django 2.1.2 on 2020-04-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200426_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
    ]
