# Generated by Django 2.1.2 on 2020-04-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200426_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_Body',
        ),
    ]
