# Generated by Django 2.1.2 on 2020-04-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_service_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('icon', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
