# Generated by Django 2.1.2 on 2020-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_category_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=50)),
            ],
        ),
    ]
