# Generated by Django 2.1.2 on 2020-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_clientquote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientquote',
            name='quote',
            field=models.TextField(),
        ),
    ]
