# Generated by Django 2.1.2 on 2020-04-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_technique_technique_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('projects', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.Projects')),
            ],
        ),
    ]
