# Generated by Django 2.1.2 on 2020-04-28 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_projectsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category'),
        ),
        migrations.AlterField(
            model_name='projectsimage',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
