# Generated by Django 2.1.2 on 2020-04-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200428_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_detail_heading',
            field=models.CharField(default='heading', max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_detail_subheading',
            field=models.TextField(default='sub-heading'),
        ),
    ]
