# Generated by Django 2.1.2 on 2020-04-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200429_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_detail_heading',
            field=models.CharField(default='heading', max_length=200),
        ),
    ]
