# Generated by Django 2.1.2 on 2020-04-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200427_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_tag',
            name='services',
        ),
        migrations.DeleteModel(
            name='Service_Tag',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
